// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SigProc.infra.dados.Contextos;

#nullable disable

namespace SigProc.infra.dados.Migrations
{
    [DbContext(typeof(SqlServidorContexto))]
    partial class SqlServidorContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SigProc.Domain.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEdicao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataNasc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matricula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("SigProc.Domimio.Entidades.DadosDeTramitacaoSicop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Concad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataDoDespacho_01")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataDoDespacho_02")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataDoDespacho_03")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataDoDespacho_04")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataDoDespacho_05")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataDoDespacho_06")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataDoDespacho_07")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataDoDespacho_08")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataDoDespacho_09")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataDoDespacho_10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataDoDespacho_11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataDoDespacho_12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataDoDespacho_13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataDoDespacho_14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataEdicao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Despacho_01")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Despacho_02")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Despacho_03")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Despacho_04")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Despacho_05")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Despacho_06")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Despacho_07")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Despacho_08")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Despacho_09")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Despacho_10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Despacho_11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Despacho_12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Despacho_13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Despacho_14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guia_01")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guia_02")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guia_03")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guia_04")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guia_05")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guia_06")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guia_07")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guia_08")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guia_09")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guia_10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guia_11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guia_12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guia_13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guia_14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_01")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_02")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_03")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_04")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_05")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_06")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_07")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_08")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_09")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatDig_01")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatDig_02")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatDig_03")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatDig_04")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatDig_05")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatDig_06")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatDig_07")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatDig_08")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatDig_09")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatDig_10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatDig_11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatDig_12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatDig_13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatDig_14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatRec_01")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatRec_02")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatRec_03")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatRec_04")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatRec_05")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatRec_06")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatRec_07")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatRec_08")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatRec_09")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatRec_10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatRec_11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatRec_12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatRec_13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatRec_14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDoProcesso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opcao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgaoDeDestino_01")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgaoDeDestino_02")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgaoDeDestino_03")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgaoDeDestino_04")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgaoDeDestino_05")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgaoDeDestino_06")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgaoDeDestino_07")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgaoDeDestino_08")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgaoDeDestino_09")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgaoDeDestino_10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgaoDeDestino_11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgaoDeDestino_12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgaoDeDestino_13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgaoDeDestino_14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rotina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sequencia_01")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sequencia_02")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sequencia_03")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sequencia_04")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sequencia_05")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sequencia_06")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sequencia_07")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sequencia_08")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sequencia_09")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sequencia_10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sequencia_11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sequencia_12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sequencia_13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sequencia_14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("StatusLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DadosDeTramitacaoSicop");
                });

            modelBuilder.Entity("SigProc.Domimio.Entidades.DadosDoProcessoSicop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AutoDeInfracao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoAssunto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataDeCadastroDeProcesso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataDeDespachoTramitacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataDeRecebimentoTramitacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataDigitacaoTramitacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataDoProcesso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataEdicao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoDoTipoDoDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DespachoProcessoTramitacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentacaoDoIdentificador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoDestinoProcessoTramitacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoraDeCadastroDoProcesso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentificacaoProcesso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InformacaoComplementar1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InformacaoComplementar2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InformacaoComplementar3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InformacaoTela")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InformacaoTela1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InformacaoTela10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InformacaoTela11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InformacaoTela12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InformacaoTela2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InformacaoTela3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InformacaoTela4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InformacaoTela5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InformacaoTela6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InformacaoTela7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InformacaoTela8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InformacaoTela9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InformacaoVolume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatriculaDigitadorProcesso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatriculaDigitadorTramitacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatriculaDoDespachoTramitacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatriculaDoRecebedorTramitacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatriculaRecebedorCadastro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeDoRequerente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NovoPosicionamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDoProcesso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDoTipoDoDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroGuiaTramitacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgaoDeOrigem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgaoDestinoTramitacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgaoDoDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgaoOrigemTramitacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PastaDeAssentamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessoPrincipal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rotina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SequenciaTramitacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("StatusLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDoDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DadosDoProcessoSicop");
                });

            modelBuilder.Entity("SigProc.Dominio.Entidades.Gerencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEdicao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdUsuarioResp")
                        .HasColumnType("int");

                    b.Property<int>("Prazo")
                        .HasColumnType("int");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuarioResp");

                    b.ToTable("Gerencia");
                });

            modelBuilder.Entity("SigProc.Dominio.Entidades.GerenciaPrazo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEdicao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdGerencia")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoContratacao")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoPrazo")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoProcesso")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioCadastro")
                        .HasColumnType("int");

                    b.Property<int>("Prazo")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdGerencia");

                    b.HasIndex("IdTipoContratacao");

                    b.HasIndex("IdTipoPrazo");

                    b.HasIndex("IdTipoProcesso");

                    b.ToTable("GerenciaPrazo");
                });

            modelBuilder.Entity("SigProc.Dominio.Entidades.GerenciaUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEdicao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdGerencia")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoUsuarioGerencia")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioCadastro")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioGerencia")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdGerencia");

                    b.HasIndex("IdTipoUsuarioGerencia");

                    b.HasIndex("IdUsuarioCadastro");

                    b.HasIndex("IdUsuarioGerencia");

                    b.ToTable("GerenciaUsuario");
                });

            modelBuilder.Entity("SigProc.Dominio.Entidades.Processo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataCadastroProc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEdicao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataUltimaTramProc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdTipoContratacao")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoProcesso")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioCadastro")
                        .HasColumnType("int");

                    b.Property<string>("InfoComplementar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumDoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumProcesso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgaoCadastro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgaoDestino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgaoOrigem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requerente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("TipoDoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoContratacao");

                    b.HasIndex("IdTipoProcesso");

                    b.HasIndex("IdUsuarioCadastro");

                    b.ToTable("Processo");
                });

            modelBuilder.Entity("SigProc.Dominio.Entidades.ProcessoTramitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEdicao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEnvio")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPrazo")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataTramitacao")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<int>("IdOrgaoDestino")
                        .HasColumnType("int");

                    b.Property<int>("IdOrgaoOrigem")
                        .HasColumnType("int");

                    b.Property<int>("IdProcesso")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioTramitacao")
                        .HasColumnType("int");

                    b.Property<string>("NumeroProcesso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prazo")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("TempoEnvio")
                        .HasColumnType("int");

                    b.Property<int?>("TempoPrazo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdOrgaoDestino");

                    b.HasIndex("IdOrgaoOrigem");

                    b.HasIndex("IdProcesso");

                    b.HasIndex("IdUsuarioTramitacao");

                    b.ToTable("ProcessoTramitacao");
                });

            modelBuilder.Entity("SigProc.Dominio.Entidades.TipoContratacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEdicao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TipoContratacao");
                });

            modelBuilder.Entity("SigProc.Dominio.Entidades.TipoPrazo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEdicao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TipoPrazo");
                });

            modelBuilder.Entity("SigProc.Dominio.Entidades.TipoProcesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEdicao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TipoProcesso");
                });

            modelBuilder.Entity("SigProc.Dominio.Entidades.TipoUsuarioGerencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEdicao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TipoUsuarioGerencia");
                });

            modelBuilder.Entity("SigProc.Dominio.Entidades.Gerencia", b =>
                {
                    b.HasOne("SigProc.Domain.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuarioResp")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SigProc.Dominio.Entidades.GerenciaPrazo", b =>
                {
                    b.HasOne("SigProc.Dominio.Entidades.Gerencia", "Gerencia")
                        .WithMany()
                        .HasForeignKey("IdGerencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SigProc.Dominio.Entidades.TipoContratacao", "TipoContratacao")
                        .WithMany()
                        .HasForeignKey("IdTipoContratacao");

                    b.HasOne("SigProc.Dominio.Entidades.TipoPrazo", "TipoPrazo")
                        .WithMany()
                        .HasForeignKey("IdTipoPrazo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SigProc.Dominio.Entidades.TipoProcesso", "TipoProcesso")
                        .WithMany()
                        .HasForeignKey("IdTipoProcesso");

                    b.Navigation("Gerencia");

                    b.Navigation("TipoContratacao");

                    b.Navigation("TipoPrazo");

                    b.Navigation("TipoProcesso");
                });

            modelBuilder.Entity("SigProc.Dominio.Entidades.GerenciaUsuario", b =>
                {
                    b.HasOne("SigProc.Dominio.Entidades.Gerencia", "Gerencia")
                        .WithMany()
                        .HasForeignKey("IdGerencia")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SigProc.Dominio.Entidades.TipoUsuarioGerencia", "TipoUsuarioGerencia")
                        .WithMany()
                        .HasForeignKey("IdTipoUsuarioGerencia")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SigProc.Domain.Entidades.Usuario", "UsuarioCadastro")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCadastro")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SigProc.Domain.Entidades.Usuario", "UsuarioGerencia")
                        .WithMany()
                        .HasForeignKey("IdUsuarioGerencia")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Gerencia");

                    b.Navigation("TipoUsuarioGerencia");

                    b.Navigation("UsuarioCadastro");

                    b.Navigation("UsuarioGerencia");
                });

            modelBuilder.Entity("SigProc.Dominio.Entidades.Processo", b =>
                {
                    b.HasOne("SigProc.Dominio.Entidades.TipoContratacao", "TipoContratacao")
                        .WithMany()
                        .HasForeignKey("IdTipoContratacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SigProc.Dominio.Entidades.TipoProcesso", "TipoProcesso")
                        .WithMany()
                        .HasForeignKey("IdTipoProcesso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SigProc.Domain.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCadastro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoContratacao");

                    b.Navigation("TipoProcesso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SigProc.Dominio.Entidades.ProcessoTramitacao", b =>
                {
                    b.HasOne("SigProc.Dominio.Entidades.Gerencia", "GerenciaDestino")
                        .WithMany()
                        .HasForeignKey("IdOrgaoDestino")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SigProc.Dominio.Entidades.Gerencia", "GerenciaOrigem")
                        .WithMany()
                        .HasForeignKey("IdOrgaoOrigem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SigProc.Dominio.Entidades.Processo", "Processo")
                        .WithMany()
                        .HasForeignKey("IdProcesso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SigProc.Domain.Entidades.Usuario", "UsuarioTramitacao")
                        .WithMany()
                        .HasForeignKey("IdUsuarioTramitacao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GerenciaDestino");

                    b.Navigation("GerenciaOrigem");

                    b.Navigation("Processo");

                    b.Navigation("UsuarioTramitacao");
                });
#pragma warning restore 612, 618
        }
    }
}
